### ISSUE TITLE
Plex Error - Google Chrome

### ISSUE THREAD

**Issue by Simpuhl** [SpaceK33z/movieo-to-plex#172]
Describe the bug:

I load any movie on IMDB and I get Plex Error after a few seconds of waiting.

To Reproduce:

Just visit IMDB.com with Google Chrome/Web To Plex addin

Expected behavior;

It should tell me if I have the movie or not

Extension Information
Not sure how to get the version but its the latest one from the Google Chrome Store
Windows 10 Pro

Screenshot: https://imgur.com/pKfGraA

**Comment by Ephellon** [comment]
Hi, could you give me some more details please?

**Comment by Ephellon** [comment]
**Describe the bug**
*A clear and concise (to the point) description of what the bug is*

**To Reproduce**
*Steps to reproduce the behavior*
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

**Expected behavior**
*A clear and concise (to the point) description of what you expected to happen*

**Screenshots**
*If applicable, add screenshots to help explain your problem*

**Extension Information**
 - Version: `4.XXXX.YYYY.ZZZZ`
 - Source: `store` `GitHub`
 - Browser: `chrome` `firefox` `edge` `opera`
 - Operating System: `Windows` `Mac` `*nix`

**Additional comments**
*Add any other comments about the problem here, such as how often the issue occurs, any new changes, etc*

**Comment by Simpuhl** [comment]
Describe the bug:

I load any movie on IMDB and I get Plex Error after a few seconds of waiting.

To Reproduce:

Just visit IMDB.com with Google Chrome/Web To Plex addin

Expected behavior;

It should tell me if I have the movie or not

Extension Information
Not sure how to get the version but its the latest one from the Google Chrome Store
Windows 10 Pro

Screenshot:  https://imgur.com/pKfGraA

**Comment by Ephellon** [comment]
To get the version, right click on the icon and select "options"

**Comment by Ephellon** [comment]
From what I could see, you're using the outdated version, please see the Wiki or README to update

**Comment by Simpuhl** [comment]
Version is 3.4

The one in the Chrome Store isn't going to be updated anymore?

**Comment by Simpuhl** [comment]
Ok so I guess theres two versions...

https://chrome.google.com/webstore/detail/web-to-plex/kmcinnefmnkfnmnmijfmbiaflncfifcn

and 

https://chrome.google.com/webstore/detail/web-to-plex/cbpdknicmfolbdpakjihphblioajkcfl

I am going to install the second version with Version
4.1.2.4

**Comment by Ephellon** [comment]
Hi. That is correct as of now, the first one is no longer being maintained
